name := "dashboard"
version := "1.0"
scalaVersion := "2.11.12"
libraryDependencies += "org.apache.spark" %%  "spark-core" % "2.4.6"
libraryDependencies += "org.apache.spark" %%  "spark-sql" % "2.4.6"
libraryDependencies += "org.apache.spark" %%  "spark-mllib" % "2.4.6"
libraryDependencies += "org.elasticsearch" %% "elasticsearch-spark-20" % "6.8.9"